### ISSUE TITLE
Installation is failing as the vendor's exe file has been renamed

### ISSUE THREAD

**Issue by anthonymbower** [skyguy94/chocolatey-packages#27]
Hi,

Installing this package via chocolatey is failing. The vendor has confirmed that the IISCryptoCli40.exe no longer exists and that a redirect that has been in place for sometime has recently been removed.

The steps to recreate are to simply install via chocolatey:
`choco install iiscrypto-cli`

The result is:
Chocolatey v0.10.15
Installing the following packages:
iiscrypto-cli
By installing you accept licenses for the packages.
Progress: Downloading iiscrypto-cli 3.0... 100%

iiscrypto-cli v3.0 [Approved]
iiscrypto-cli package files install completed. Performing other installation steps.
The package iiscrypto-cli wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): Y

Downloading iiscrypto-commandline
  from 'https://www.nartac.com/Downloads/IISCrypto/IISCryptoCli.exe'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\iiscrypto-cli\Tools\iiscryptocli.exe (261.57 KB).
Download of iiscryptocli.exe (261.57 KB) completed.
C:\ProgramData\chocolatey\lib\iiscrypto-cli\Tools\iiscryptocli.exe
Attempt to get headers for https://www.nartac.com/Products/IISCrypto/IISCryptoCli40.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nartac.com/Products/IISCrypto/IISCryptoCli40.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading iiscrypto-commandline
  from 'https://www.nartac.com/Products/IISCrypto/IISCryptoCli40.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.nartac.com/Products/IISCrypto/IISCryptoCli40.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of iiscrypto-cli was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\iiscrypto-cli\Tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - iiscrypto-cli (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\iiscrypto-cli\Tools\ChocolateyInstall.ps1'.
 See log for details.

**Comment by kpakkiriswamy-clgx** [comment]
We are also experiencing this issue with the package pointing to a broken URL. Appreciate if this issue can be assigned for a fix.

**Comment by skyguy94** [comment]
The updated package got approved yesterday. Let me know if there are any more issues.
