### ISSUE TITLE
Would be great to add an option for "listening port" for the server

### ISSUE THREAD

**Issue by espoelstra** [skyguy94/chocolatey-packages#3]
This requires modifying the tomcat XML in order to replace the default port 8111 to change it to whatever the user supplies (typically probably port 80).

I wrote a PowerShell snippet that does this, but haven't quite figured out how it would fit into the current chocolatey package the way it is written. Would need to reference the install path given by the user and check for their preferred port's presence in the config file, otherwise change the default to their custom port.

```
# Make TeamCity listen on port 80 instead of 8111
# This could be cleaner with XML config parsing,
# but that's overkill since there are multiple tags and some are in commented blocks
# Just change all instances for now
(gc .\TeamCity\conf\server.xml | foreach { $_ -replace "8111","80" }) | Set-Content .\TeamCity\conf\server.xml
```

**Comment by skyguy94** [comment]
I don't think that this behavior belongs in the package but in a post install step. The package options are only what is provided by the package itself.

**Comment by espoelstra** [comment]
If a user were instead using the msi installer, it gives them the option to select a port in 9.1.x and higher I believe. I agree a lot of the configuration could happen as part of a larger configuration management system, but a lot of developers who are just trying to get an instance running on their desk may not have the time to shave those yaks. Locating the correct installation path from a configuration management tool could also be a challenge if not overriding the default path since the TeamCity Server doesn't really have an .exe that is part of the PATH where you could hunt it down.

**Comment by espoelstra** [comment]
In chatting with Rob in the choco channel I think he presented an option that solves both goals, move the extra config to another package that depends on the teamcity server package and takes the parameters that customize the base package beyond just installation arguments, ie memory settings/port changes/etc.
https://gitter.im/chocolatey/choco?at=5825fc08e462097a3038589e

**Comment by skyguy94** [comment]
Cool. I just skimmed that convo. I think its a worthwhile approach.
