### ISSUE TITLE
In the case of a 64 bit Java (which server-jre provides) JetBrains recommends doubling the default heap size 

### ISSUE THREAD

**Issue by espoelstra** [skyguy94/chocolatey-packages#4]
It would be great to accept the JVM settings as parameters, but even just statically modifying this during the install while writing the TeamCityServer.properties file would be an improvement. This shouldn't be terrible as the server.bat files simply require JVM options to be in an environment variable.

Eg: `$env:TEAMCITY_SERVER_MEM_OPTS='-Xmx4g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m'` which can be set via Install-ChocolateyEnvironmentVariable.

The link below gives the recommended sizes for 32 and 64 bit Java with N agents/jobs.
https://confluence.jetbrains.com/display/TCD9/Installing+and+Configuring+the+TeamCity+Server#InstallingandConfiguringtheTeamCityServer-Using64bitJavatoRunTeamCityServer

**Comment by skyguy94** [comment]
I think this can be set by an install script.  I set this and the memory options and data path via powershell during install. I don't think the goal of this package is to configure possible options (SSL/IIS reverse proxy/etc..) that could be applied to tomcat, but to install the package as it comes from the vendor with the overrides that the vendor provides.

**Comment by espoelstra** [comment]
In chatting with Rob in the choco channel I think he presented an option that solves both goals, move the extra config to another package that depends on the teamcity server package and takes the parameters that customize the base package beyond just installation arguments, ie memory settings/port changes/etc.
https://gitter.im/chocolatey/choco?at=5825fc08e462097a3038589e
